FROM maven:alpine


WORKDIR /app
ADD pom.xml /app
RUN mvn verify clean --fail-never


COPY . /app
RUN mvn -v
RUN mvn clean install -DskipTests
EXPOSE 8080
RUN chmod 7777 ./target/app.jar
CMD ["java","-jar","./target/app.jar"]